/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Color = { 'red' : null } |
  { 'blue' : null } |
  { 'green' : null } |
  { 'black' : null } |
  { 'white' : null } |
  { 'yellow' : null };
export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'id' : string,
  'status' : InquiryStatus,
  'serviceType' : ServiceType,
  'user' : Principal,
  'email' : string,
  'message' : string,
  'replies' : Array<string>,
}
export type InquiryStatus = { 'open' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'paymentSessionId' : [] | [string],
  'user' : Principal,
  'items' : Array<TShirt>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : string,
  'availableColors' : Array<Color>,
  'name' : string,
  'description' : string,
  'availableSizes' : Array<Size>,
  'image' : ExternalBlob,
  'priceCents' : bigint,
}
export type ServiceType = { 'modeling3D' : null } |
  { 'videoEditing' : null } |
  { 'websiteDesign' : null } |
  { 'contentCreation' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type Size = { 'l' : null } |
  { 'm' : null } |
  { 's' : null } |
  { 'xl' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TShirt {
  'color' : Color,
  'size' : Size,
  'productId' : string,
  'quantity' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInquiryReply' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProduct' : ActorMethod<[Product], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiry' : ActorMethod<[string], Inquiry>,
  'getOrder' : ActorMethod<[string], Order>,
  'getProduct' : ActorMethod<[string], Product>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserInquiries' : ActorMethod<[Principal], Array<Inquiry>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[Order], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitInquiry' : ActorMethod<[Inquiry], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateInquiryStatus' : ActorMethod<[string, InquiryStatus], undefined>,
  'updateOrderPayment' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];